import { create } from "zustand";
import { persist } from "zustand/middleware";

export const useContactStore = create(
  persist((set) => ({
    contacts: [
      {
        contactId: 1,
        contactName: "John",
        contactUserName: "john",
        contactAvatar: "https://i.pravatar.cc/150?img=12",
        contactLastMessage: "Get the cash on your way here.",
        lastMessageTime: "2026-06-10T09:08:00Z",
      },
      {
        contactId: 2,
        contactName: "Ella",
        contactUserName: "ella",
        contactAvatar: "https://i.pravatar.cc/150?img=32",
        contactLastMessage: "What is wrong with the dog?",
        lastMessageTime: "2026-06-15T09:08:00Z",
      },
      {
        contactId: 3,
        contactName: "Michael",
        contactUserName: "michael",
        contactAvatar: "https://i.pravatar.cc/150?img=15",
        contactLastMessage: "I'm already outside.",
        lastMessageTime: "2026-06-16T18:42:00Z",
      },
      {
        contactId: 4,
        contactName: "Sophia",
        contactUserName: "sophia",
        contactAvatar: "https://i.pravatar.cc/150?img=44",
        contactLastMessage: "Send me the design when you're done.",
        lastMessageTime: "2026-06-17T11:23:00Z",
      },
      {
        contactId: 5,
        contactName: "David",
        contactUserName: "david",
        contactAvatar: "https://i.pravatar.cc/150?img=18",
        contactLastMessage: "😂😂 That was actually funny.",
        lastMessageTime: "2026-06-18T21:15:00Z",
      },
      {
        contactId: 6,
        contactName: "Grace",
        contactUserName: "grace",
        contactAvatar: "https://i.pravatar.cc/150?img=47",
        contactLastMessage: "Don't forget the meeting tomorrow.",
        lastMessageTime: "2026-06-19T07:30:00Z",
      },
      {
        contactId: 7,
        contactName: "Daniel",
        contactUserName: "daniel",
        contactAvatar: "https://i.pravatar.cc/150?img=23",
        contactLastMessage: "I just got home.",
        lastMessageTime: "2026-06-20T20:11:00Z",
      },
      {
        contactId: 8,
        contactName: "Olivia",
        contactUserName: "olivia",
        contactAvatar: "https://i.pravatar.cc/150?img=49",
        contactLastMessage: "Can you review this for me?",
        lastMessageTime: "2026-06-21T13:58:00Z",
      },
      {
        contactId: 9,
        contactName: "James",
        contactUserName: "james",
        contactAvatar: "https://i.pravatar.cc/150?img=25",
        contactLastMessage: "Running a little late.",
        lastMessageTime: "2026-06-22T17:47:00Z",
      },
      {
        contactId: 10,
        contactName: "Emma",
        contactUserName: "emma",
        contactAvatar: "https://i.pravatar.cc/150?img=50",
        contactLastMessage: "The photos look amazing ❤️",
        lastMessageTime: "2026-06-23T16:29:00Z",
      },
      {
        contactId: 11,
        contactName: "Chris",
        contactUserName: "chris",
        contactAvatar: "https://i.pravatar.cc/150?img=28",
        contactLastMessage: "Let's grab lunch later.",
        lastMessageTime: "2026-06-24T12:05:00Z",
      },
      {
        contactId: 12,
        contactName: "Ava",
        contactUserName: "ava",
        contactAvatar: "https://i.pravatar.cc/150?img=55",
        contactLastMessage: "I'll call you in five minutes.",
        lastMessageTime: "2026-06-25T19:40:00Z",
      },
      {
        contactId: 13,
        contactName: "Noah",
        contactUserName: "noah",
        contactAvatar: "https://i.pravatar.cc/150?img=30",
        contactLastMessage: "Where are you now?",
        lastMessageTime: "2026-06-26T10:16:00Z",
      },
      {
        contactId: 14,
        contactName: "Mia",
        contactUserName: "mia",
        contactAvatar: "https://i.pravatar.cc/150?img=59",
        contactLastMessage: "Thank you so much 😊",
        lastMessageTime: "2026-06-27T15:32:00Z",
      },
      {
        contactId: 15,
        contactName: "Ethan",
        contactUserName: "ethan",
        contactAvatar: "https://i.pravatar.cc/150?img=35",
        contactLastMessage: "See you this weekend!",
        lastMessageTime: "2026-06-28T08:55:00Z",
      },
    ],
    name: "chats-storage",

  }))
);
