import { create } from "zustand";

export const useNotificationStore = create(() => ({
  notifications: [
    {
      notificationId: 1,
      receiverId: 0,
      actorId: 5,
      type: "like",
      actorName: "Sarah Johnson",
      actorAvatar: "https://i.pravatar.cc/150?img=5",
      postText:
        "Building side projects consistently beats waiting for the perfect idea.",
      targetId: 1,
      createdAt: "2026-08-03T08:15:00Z",
      isRead: false,
    },
    {
      notificationId: 2,
      receiverId: 0,
      actorId: 12,
      type: "like",
      actorName: "Ava White",
      actorAvatar: "https://i.pravatar.cc/150?img=50",
      postText: "",
      targetId: null,
      createdAt: "2026-08-03T08:01:00Z",
      isRead: false,
    },
    {
      notificationId: 3,
      receiverId: 0,
      actorId: 3,
      type: "repost",
      actorName: "Michael Brown",
      actorAvatar: "https://i.pravatar.cc/150?img=15",
      postText: "Frontend performance is underrated in most projects.",
      targetId: 3,
      createdAt: "2026-08-03T07:47:00Z",
      isRead: false,
    },
    {
      notificationId: 4,
      receiverId: 0,
      actorId: 18,
      type: "like",
      actorName: "Mia Walker",
      actorAvatar: "https://i.pravatar.cc/150?img=65",
      postText: "You should definitely check this out @you",
      targetId: 18,
      createdAt: "2026-08-03T07:18:00Z",
      isRead: true,
    },
    {
      notificationId: 5,
      receiverId: 0,
      actorId: 7,
      type: "repost",
      actorName: "Daniel Moore",
      actorAvatar: "https://i.pravatar.cc/150?img=25",
      postText: "Nothing beats shipping features and learning from users.",
      targetId: 7,
      createdAt: "2026-08-03T06:55:00Z",
      isRead: true,
    },
    {
      notificationId: 6,
      receiverId: 0,
      actorId: 14,
      type: "like",
      actorName: "Charlotte Hall",
      actorAvatar: "https://i.pravatar.cc/150?img=56",
      postText: "I need more apps that prioritize speed over endless features.",
      targetId: 14,
      createdAt: "2026-08-03T06:21:00Z",
      isRead: false,
    },
    {
      notificationId: 7,
      receiverId: 0,
      actorId: 9,
      type: "repost",
      actorName: "Ethan Anderson",
      actorAvatar: "https://i.pravatar.cc/150?img=40",
      postText: "Coffee and dark mode continue to carry my entire career.",
      targetId: 9,
      createdAt: "2026-08-03T05:54:00Z",
      isRead: true,
    },
    {
      notificationId: 8,
      receiverId: 0,
      actorId: 16,
      type: "like",
      actorName: "Amelia Harris",
      actorAvatar: "https://i.pravatar.cc/150?img=60",
      postText: "",
      targetId: null,
      createdAt: "2026-08-03T05:12:00Z",
      isRead: false,
    },
    {
      notificationId: 9,
      receiverId: 0,
      actorId: 20,
      type: "like",
      actorName: "Harper King",
      actorAvatar: "https://i.pravatar.cc/150?img=70",
      postText: "I really enjoy building products from scratch.",
      targetId: 20,
      createdAt: "2026-08-03T04:36:00Z",
      isRead: true,
    },
    {
      notificationId: 10,
      receiverId: 0,
      actorId: 2,
      type: "repost",
      actorName: "David Wilson",
      actorAvatar: "https://i.pravatar.cc/150?img=12",
      postText: "Interesting point by @you 👏",
      targetId: 2,
      createdAt: "2026-08-03T03:59:00Z",
      isRead: false,
    },
    {
      notificationId: 11,
      receiverId: 0,
      actorId: 19,
      type: "repost",
      actorName: "William Scott",
      actorAvatar: "https://i.pravatar.cc/150?img=68",
      postText: "Consistency is more important than intensity.",
      targetId: 19,
      createdAt: "2026-08-03T03:20:00Z",
      isRead: false,
    },
    {
      notificationId: 12,
      receiverId: 0,
      actorId: 4,
      type: "like",
      actorName: "Emily Davis",
      actorAvatar: "https://i.pravatar.cc/150?img=20",
      postText: "The best debugging sessions happen after a short walk.",
      targetId: 4,
      createdAt: "2026-08-03T02:48:00Z",
      isRead: true,
    },
    {
      notificationId: 13,
      receiverId: 0,
      actorId: 11,
      type: "repost",
      actorName: "Benjamin Lee",
      actorAvatar: "https://i.pravatar.cc/150?img=47",
      postText: "",
      targetId: null,
      createdAt: "2026-08-03T02:10:00Z",
      isRead: false,
    },
    {
      notificationId: 14,
      receiverId: 0,
      actorId: 17,
      type: "repost",
      actorName: "Alexander Lewis",
      actorAvatar: "https://i.pravatar.cc/150?img=63",
      postText: "A clean UI always feels faster.",
      targetId: 17,
      createdAt: "2026-08-03T01:42:00Z",
      isRead: false,
    },
    {
      notificationId: 15,
      receiverId: 0,
      actorId: 10,
      type: "like",
      actorName: "Grace Thomas",
      actorAvatar: "https://i.pravatar.cc/150?img=45",
      postText: "Spent today refactoring old code and honestly enjoyed it.",
      targetId: 10,
      createdAt: "2026-08-03T01:05:00Z",
      isRead: true,
    },
  ],
}));
